# Generated by Django 2.0.7 on 2018-07-14 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('timestamp',), 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
