# Generated by Django 2.0.7 on 2018-07-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='studentNo',
            new_name='studentname',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_grade',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default=1234, max_length=30),
            preserve_default=False,
        ),
    ]
